version: '3'
services:
  db:
    image: postgres
    env_file: .env
  web:
    build:
      context: ./
      dockerfile: /Dockerfile
    command: bash -c "rm -f ls; /tmp/pids/server.pid; rails db:create; rails db:migrate; rails s -p 80 -b 'web'"
    volumes:
      - ./:/web
    ports:
      - "80:80"
    depends_on:
      - db
    env_file: .env
